apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: age-calculator
  template:
    metadata:
      labels:
        app: age-calculator
    spec:
      containers:
      - name: age-calculator
        image: gcr.io/clever-cyclist-412815/age-calculator:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: age-calculator-service
spec:
  selector:
    app: age-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
